### PR TITLE
Progress bar added

### PR DESCRIPTION
**Pull request by Thilagavathi1**
Progress bar for displaying PR counts.

### CODE REVIEW

**Comment by Thilagavathi1** [comment]
@rowhitswami ,Created PR for the progressbar.

**Comment by rowhitswami** [comment]
@Thilagavathi1 Thanks for your great work. I request you to add some appropriate and exciting text below progress bar explaining the status of the user. The text should be different for each individual status.
Hope you got my point :blush:

**Comment by PritiKumr** [comment]
@rowhitswami That could be made a separate PR if desired. Why not raise an issue and anyone can look into it?

**Comment by rowhitswami** [comment]
@PritiKumr Yes, open an issue and start working on it if you wish. :blush:

**Pull request merged**
