### PR TITLE
Prettied Up The Display Of Pull Requests

### PR DESCRIPTION
**Pull request by Occult-Dev**
did some simple css work and now each pull request shows up in a card, along with a simple png showing the state of the PR. ( _addresses #3_ )

kept all the css in the index file, wasn't sure if you wanted it moved to a separate file or not.

oh yeah, also removed a rogue </head> tag that was floating around for some reason ¯\_(ツ)_/¯

### CODE REVIEW

**Comment by willypt** [comment]
Hi, just to add some note.
Closed state in the API used here doesn't necessarily mean it's `merged`.
You have to check the PR via API and get the `merged_at` attribute
https://developer.github.com/v3/pulls/

**Comment by rowhitswami** [comment]
Hey @StuffBySpencer thanks for your great effort. However, some modifications needed:
* Make the width of the cards 50% in the middle.
* Make the image responsive according to the screen of the device.
* Please add all css in file located in css folder.

Thank you again :blush:

**Comment by Occult-Dev** [comment]
Thanks for the feedback.
I overlooked that you were using bootstrap, so I went ahead and changed the format over to a simple grid which should cover most of the responsive tasks.

As for the merged_at attribute that @willypt is talking about, I'm afraid I couldn't get that to work. I see it listed in the API docs, but it's not showing up in the request. Maybe I'm missing something? Is it a different call you have to make to get that bit of info? Any help on this would be appreciated.

Let me know if there's more I should fix!

**Comment by rowhitswami** [comment]
@StuffBySpencer I'm merging your pull request :blush: 
Feel free to add any other functionality 
Thank you

**Comment by willypt** [comment]
@StuffBySpencer You basically need to make another API call. If you take a look at my fork & PR #5 , you can also start from there by separating all API and load them async-ly 😃 

If you use GraphQL API, it should be easier though

**Comment by rowhitswami** [comment]
@willypt I just checked and it is working fine. It is showing whether a PR is open or closed :blush:

**Comment by willypt** [comment]
Let me do a quick example, I'll open an issue regarding this though it is out of scope as the DigitalOcean TnC says that we need to open 4 pull requests. Might as well learn and sharing together about GitHub API! 😃

**Comment by rowhitswami** [comment]
@willypt yes of course. I'm closing your recent PR. Please do fork again as head of the master branch is ahead from your branch. Also please make another branch for experimenting these stuff.

**Comment by willypt** [comment]
Sure, this project is great and can be used for future Hacktoberfest! Here's the said issue #16

**Pull request merged**
