### PR TITLE
Enhance Card Style (HTML, CSS)

### LINKED ISSUE #18: Enhance Card Style (HTML, CSS)
Good for the first timer. You need to style the card (in which the data of pull requests is being fetched) however you want it to be. The only condition is it should look elegant. Want to add new feature/change/improve something else??
 Come up with your suggestion and open an issue :blush:

### PR DESCRIPTION
**Pull request by kalpanibhagya**
This Fix #18

### CODE REVIEW

**Comment by kalpanibhagya** [comment]
Request for review : @rowhitswami

**Comment by rowhitswami** [comment]
Hello @kalpanibhagya I reviewed your changes and found out there's no much visual difference. Please avoid thing which makes the code more complex. Can you make it more attractive?

**Comment by kalpanibhagya** [comment]
Sure . I'll do that. :)

**Comment by rowhitswami** [comment]
@kalpanibhagya I'm waiting for your response.

**Comment by rowhitswami** [comment]
@kalpanibhagya I'm closing this PR as I got no response from your side. 
Please create a PR again if you wish to work on this issue in future.

**Comment by kalpanibhagya** [comment]
I'm really sorry for the delay . I created a new PR @rowhitswami

**Pull request closed without merging**
