### PR TITLE
Added Hyperlinks, description. Improved tags, Improved CSS

### PR DESCRIPTION
**Pull request by vipulgupta2048**
Helps out in making the UI better and making the tool look more informative.
Also removed many extra lines, spaces and tab in the code. Improves readability and similar to standard format.

### CODE REVIEW

**Comment by rowhitswami** [comment]
@vipulgupta2048 thank you for your great work :blush:

**Comment by vipulgupta2048** [comment]
@rowhitswami Hey, I am checking out the website now. And I don't see any website description that I added. I like to know the reason for its removal

**Comment by rowhitswami** [comment]
@vipulgupta2048 yes dear, I merged your pull request but then I removed the content that should not be there. However, meta tags are kept.

**Comment by vipulgupta2048** [comment]
Cool. It is your website, after all. No issues.

**Pull request merged**
